Numpy

-Numerical pythan

On "Arrays"
l1=["india","us",45,-4.5]

A1=["india","us","china","pakisthan"] #must be same datatype

-generate random numbders

-numerical analysis

In [1]:
import numpy as np   #np is the alias name

In [2]:
my_list=[2,3,4,5,6]

In [3]:
print(my_list)

[2, 3, 4, 5, 6]


In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list)  #np.array() convert any list into an array

In [6]:
print(arr)

[2 3 4 5 6]


In [7]:
type(arr)  #ndimentional array, n=1 i.e 1D array

numpy.ndarray

In [8]:
#multinested array
l1=[2,3,4,5,6]
l2=[4,5,6,9,3]
l3=[1,7,4,5,6]

In [9]:
arr_new=np.array([l1,l2,l3])

In [10]:
type(arr_new)  #n=2, 2D array

numpy.ndarray

In [11]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [12]:
arr_new.shape  #show the number of row and column in the array

(3, 5)

In [14]:
arr_new.reshape(5,3)

array([[2, 3, 4],
       [5, 6, 4],
       [5, 6, 9],
       [3, 1, 7],
       [4, 5, 6]])

In [15]:
print(arr_new.reshape(5,3))

[[2 3 4]
 [5 6 4]
 [5 6 9]
 [3 1 7]
 [4 5 6]]


In [16]:
#indexing and slicing

In [17]:
print(arr)

[2 3 4 5 6]


In [18]:
arr[2]

4

In [19]:
arr[2]

4

In [20]:
arr[6]

IndexError: ignored

In [21]:
arr[4]

6

In [22]:
arr[1:4]

array([3, 4, 5])

In [23]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [24]:
arr_new[1:,3:]  #1: is applicable for row and 3: is applicable for column slicing

array([[9, 3],
       [5, 6]])

In [25]:
arr_new[0:2,1:4]

array([[3, 4, 5],
       [5, 6, 9]])

In [26]:
my_list1=[4,5,6,7,8]
my_list2=[-2,6,8,3,4]
my_list3=[5,6,0,-3,5]

#convert these lists into a multinested array and fetch the given rows and columns

#arr=[0:2,2:1]
#arr=[0:2,0:2]
#arr=[1:,:4]

In [27]:
arr_new=np.array([my_list1,my_list2,my_list3])

In [28]:
print(arr_new)

[[ 4  5  6  7  8]
 [-2  6  8  3  4]
 [ 5  6  0 -3  5]]


In [29]:
arr_new[0:2,2:]

array([[6, 7, 8],
       [8, 3, 4]])

In [30]:
print(arr_new[0:2,0:2])

[[ 4  5]
 [-2  6]]


In [31]:
arr_new[1:,:4]

array([[-2,  6,  8,  3],
       [ 5,  6,  0, -3]])

In [32]:
#generate numbers

In [33]:
arr_1=np.arange(1,10)

In [34]:
print(arr_1)  #equally spaced array from 1-9

[1 2 3 4 5 6 7 8 9]


In [35]:
arr_1=np.arange(1,10,2)   #2 is the step size

In [36]:
print(arr_1)

[1 3 5 7 9]


In [37]:
np.linspace(1,10,50)  #50 indicate 50 uniquw element in the range of 1-10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [39]:
#generating random numbers

In [40]:
np.random.rand(3,4)  #here 3 is the number of rows and 4 is the number of columns
#it has a default range of 0-1(1 being exclusive in nature)  and gives floating number

array([[0.1568057 , 0.14381189, 0.41921024, 0.1788211 ],
       [0.22448868, 0.4380945 , 0.47339102, 0.36309787],
       [0.6966069 , 0.16166648, 0.20866024, 0.16350266]])

In [41]:
np.random.rand(5,5)

array([[0.487142  , 0.44718357, 0.24166188, 0.81970899, 0.01418347],
       [0.11121327, 0.45251509, 0.81818002, 0.85705268, 0.75333179],
       [0.64322322, 0.63526884, 0.62264369, 0.14575436, 0.57014442],
       [0.475478  , 0.03453676, 0.19327749, 0.58821811, 0.72516412],
       [0.73200004, 0.56272727, 0.30160772, 0.27168306, 0.32455933]])

In [42]:
np.random.randint(3,9,4)  #3,9 is the range and 4 is the number of random of elements we need in the specify range and gives interger number

array([8, 3, 3, 8])

In [43]:
np.random.randint(1,20,5)

array([ 9,  8,  6, 13,  6])